<a href="https://colab.research.google.com/github/LabdhiSheth/Deep-Learning-lab-work/blob/main/wordRNN_Prob_of_sentences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding
from nltk import sent_tokenize
from nltk import word_tokenize
import numpy

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
input_data = input("Enter a few sentences")

Enter a few sentencesJack and Jill went up the hill . To fetch a pail of water . Jack fell down and broke his crown . And Jill came tumbling after .


In [ ]:
tokenized_sent = sent_tokenize(input_data)
tokenized_sent

['Jack and Jill went up the hill .',
 'To fetch a pail of water .',
 'Jack fell down and broke his crown .',
 'And Jill came tumbling after .']

In [ ]:
tokenizer = Tokenizer(filters = '!"#$%&()*+,-/:;<=>?@[\]^_`{|}~')
tokenizer.fit_on_texts(tokenized_sent)
print(tokenizer.word_index)

{'.': 1, 'and': 2, 'jack': 3, 'jill': 4, 'went': 5, 'up': 6, 'the': 7, 'hill': 8, 'to': 9, 'fetch': 10, 'a': 11, 'pail': 12, 'of': 13, 'water': 14, 'fell': 15, 'down': 16, 'broke': 17, 'his': 18, 'crown': 19, 'came': 20, 'tumbling': 21, 'after': 22}


In [ ]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

23


In [ ]:
sequence = tokenizer.texts_to_sequences(tokenized_sent)
length = len(sequence)
print("Sequence:",sequence)
print(type(sequence))
print(length)

Sequence: [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]]
<class 'list'>
4


In [ ]:
X = []
y = []
maxlen = 0

for i in range(length):
  X.insert(i,sequence[i][:-1])
  y.insert(i,sequence[i])
  maxlen = max(maxlen,len(sequence[i]))

print(X)
print(y)
print(maxlen)

[[3, 2, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14], [3, 15, 16, 2, 17, 18, 19], [2, 4, 20, 21, 22]]
[[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]]
8


In [ ]:
X = pad_sequences(X,maxlen = maxlen+1, padding = 'pre')
print(X)
y = pad_sequences(y, maxlen = maxlen+1, padding = 'pre')
print(y)

[[ 0  0  3  2  4  5  6  7  8]
 [ 0  0  0  9 10 11 12 13 14]
 [ 0  0  3 15 16  2 17 18 19]
 [ 0  0  0  0  2  4 20 21 22]]
[[ 0  3  2  4  5  6  7  8  1]
 [ 0  0  9 10 11 12 13 14  1]
 [ 0  3 15 16  2 17 18 19  1]
 [ 0  0  0  2  4 20 21 22  1]]


In [ ]:
y = to_categorical(y,vocab_size)
y

array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]],


In [ ]:
model = Sequential()
model.add(Embedding(input_dim = vocab_size,output_dim=50))
model.add(SimpleRNN(units=70,return_sequences = True))
model.add(Dense(units=vocab_size,activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 50)          1150      
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, None, 70)          8470      
_________________________________________________________________
dense_1 (Dense)              (None, None, 23)          1633      
Total params: 11,253
Trainable params: 11,253
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print("input shape of all layers:",model.layers[0].input_shape,model.layers[1].input_shape,model.layers[2].input_shape)

input shape of all layers: (None, None) (None, None, 50) (None, None, 70)


In [ ]:
model.compile(optimizer='rmsprop',loss = 'categorical_crossentropy',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=1)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 3.1353 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 12ms/step - loss: 3.0475 - accuracy: 0.3611
Epoch 3/200
1/1 [==============================] - 0s 9ms/step - loss: 2.9677 - accuracy: 0.3333
Epoch 4/200
1/1 [==============================] - 0s 6ms/step - loss: 2.8733 - accuracy: 0.4167
Epoch 5/200
1/1 [==============================] - 0s 9ms/step - loss: 2.7691 - accuracy: 0.3889
Epoch 6/200
1/1 [==============================] - 0s 9ms/step - loss: 2.6741 - accuracy: 0.3889
Epoch 7/200
1/1 [==============================] - 0s 9ms/step - loss: 2.5923 - accuracy: 0.4167
Epoch 8/200
1/1 [==============================] - 0s 9ms/step - loss: 2.5166 - accuracy: 0.4444
Epoch 9/200
1/1 [==============================] - 0s 8ms/step - loss: 2.4436 - accuracy: 0.4444
Epoch 10/200
1/1 [==============================] - 0s 6ms/step - loss: 2.3726 - accuracy: 0.5000
Epoch 11/200
1/1 [=======

In [ ]:
def prob_of_input_sentence(model, tokenizer, sentence):
  print("Input Sentence:", sentence)
  encoded = tokenizer.texts_to_sequences([sentence])[0]
  encoded.insert(0,0)
  encoded = numpy.array(encoded)
  encoded = numpy.reshape(encoded,newshape = (1,-1))
  print("Encoded:",encoded,encoded.shape)
  prob = model.predict_proba(encoded, verbose=1)
  print("Probability:",prob,prob.shape)
  probability = 1
  for i in range(prob.shape[1]-1):
    #probability = probability * prob(0,i,encoded[0,i+1])
    probability = probability * prob[0,i,encoded[0,i+1]]
    
  print("Probability of sentence","\"",sentence,"\"","is:",probability)

In [ ]:
prob_of_input_sentence(model,tokenizer,".")

Input Sentence: .
Encoded: [[0 1]] (1, 2)
1/1 [==============================] - 0s 14ms/step
Probability: [[[9.9703276e-01 2.0084874e-04 1.8969362e-05 7.2615716e-04 6.6023854e-06
   2.2085409e-05 1.2339698e-04 6.2985651e-05 2.1342496e-05 1.2065714e-03
   1.1883777e-06 5.8769921e-05 4.0546238e-05 1.5261008e-04 2.1093027e-05
   2.7750077e-06 1.2801871e-04 3.0213960e-05 4.5324487e-05 2.4249115e-05
   2.9393579e-05 6.6631665e-06 3.7367161e-05]
  [2.5651455e-02 5.0981664e-05 1.0466456e-02 9.5162040e-01 2.9611154e-05
   2.6988813e-05 5.2712181e-05 1.3598591e-03 1.2721923e-04 8.8133331e-04
   1.8700563e-03 2.2086599e-06 1.6864600e-04 7.4092968e-05 2.4545901e-03
   4.4153263e-03 2.8789439e-06 2.9660290e-04 7.6537654e-05 2.7151118e-05
   1.9690115e-05 3.0548387e-04 1.9806997e-05]]] (1, 2, 23)
Probability of sentence " . " is: 0.00020084873540326953


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '
