<a href="https://colab.research.google.com/github/LabdhiSheth/Deep-Learning-lab-work/blob/main/word_RNNSampling_and_generating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding
from nltk import sent_tokenize
from nltk import word_tokenize
import numpy as np
from numpy import array
import numpy

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
input_data = input("Enter a few sentences")

Enter a few sentencesLong ago there lived a Rabbit in a jungle. A Tortoise also livid nearby in the same jungle. The Rabbit was always very proud of his fast pace and speed. The Rabbit always teased the Tortoise. One day he challenged the Tortoise to defeat him in a race. The Tortoise accepted the challenge. They both went to a fox and requested him to act as a judge and the fox agreed. Next day the Rabbit and the Tortoise reached the venue. They got ready to run the race. As the fox waved the flag, the two contestants started running. The Rabbit ran very swiftly. But the Tortoise ran very slowly. Covering a considerable distance, the Rabbit stopped to rest and while taking rest he fell asleep. The Tortoise ran nonstop and defeated the Rabbit in the race.


In [ ]:
tokenized_sent = sent_tokenize(input_data)
tokenized_sent

['Long ago there lived a Rabbit in a jungle.',
 'A Tortoise also livid nearby in the same jungle.',
 'The Rabbit was always very proud of his fast pace and speed.',
 'The Rabbit always teased the Tortoise.',
 'One day he challenged the Tortoise to defeat him in a race.',
 'The Tortoise accepted the challenge.',
 'They both went to a fox and requested him to act as a judge and the fox agreed.',
 'Next day the Rabbit and the Tortoise reached the venue.',
 'They got ready to run the race.',
 'As the fox waved the flag, the two contestants started running.',
 'The Rabbit ran very swiftly.',
 'But the Tortoise ran very slowly.',
 'Covering a considerable distance, the Rabbit stopped to rest and while taking rest he fell asleep.',
 'The Tortoise ran nonstop and defeated the Rabbit in the race.']

In [ ]:
tokenizer = Tokenizer(filters = '!"#$%&()*+,-/:;<=>?@[\]^_`{|}~')
tokenizer.fit_on_texts(tokenized_sent)
print(tokenizer.word_index)

{'the': 1, 'a': 2, 'rabbit': 3, 'tortoise': 4, 'and': 5, 'to': 6, 'in': 7, 'very': 8, 'race.': 9, 'fox': 10, 'ran': 11, 'jungle.': 12, 'always': 13, 'day': 14, 'he': 15, 'him': 16, 'they': 17, 'as': 18, 'rest': 19, 'long': 20, 'ago': 21, 'there': 22, 'lived': 23, 'also': 24, 'livid': 25, 'nearby': 26, 'same': 27, 'was': 28, 'proud': 29, 'of': 30, 'his': 31, 'fast': 32, 'pace': 33, 'speed.': 34, 'teased': 35, 'tortoise.': 36, 'one': 37, 'challenged': 38, 'defeat': 39, 'accepted': 40, 'challenge.': 41, 'both': 42, 'went': 43, 'requested': 44, 'act': 45, 'judge': 46, 'agreed.': 47, 'next': 48, 'reached': 49, 'venue.': 50, 'got': 51, 'ready': 52, 'run': 53, 'waved': 54, 'flag': 55, 'two': 56, 'contestants': 57, 'started': 58, 'running.': 59, 'swiftly.': 60, 'but': 61, 'slowly.': 62, 'covering': 63, 'considerable': 64, 'distance': 65, 'stopped': 66, 'while': 67, 'taking': 68, 'fell': 69, 'asleep.': 70, 'nonstop': 71, 'defeated': 72}


In [ ]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

73


In [ ]:
sequence = tokenizer.texts_to_sequences(tokenized_sent)
length = len(sequence)
print("Sequence:",sequence)
print(type(sequence))
print(length)

Sequence: [[20, 21, 22, 23, 2, 3, 7, 2, 12], [2, 4, 24, 25, 26, 7, 1, 27, 12], [1, 3, 28, 13, 8, 29, 30, 31, 32, 33, 5, 34], [1, 3, 13, 35, 1, 36], [37, 14, 15, 38, 1, 4, 6, 39, 16, 7, 2, 9], [1, 4, 40, 1, 41], [17, 42, 43, 6, 2, 10, 5, 44, 16, 6, 45, 18, 2, 46, 5, 1, 10, 47], [48, 14, 1, 3, 5, 1, 4, 49, 1, 50], [17, 51, 52, 6, 53, 1, 9], [18, 1, 10, 54, 1, 55, 1, 56, 57, 58, 59], [1, 3, 11, 8, 60], [61, 1, 4, 11, 8, 62], [63, 2, 64, 65, 1, 3, 66, 6, 19, 5, 67, 68, 19, 15, 69, 70], [1, 4, 11, 71, 5, 72, 1, 3, 7, 1, 9]]
<class 'list'>
14


In [ ]:
X = []
y = []
maxlen = 0

for i in range(length):
  X.insert(i,sequence[i][:-1])
  y.insert(i,sequence[i])
  maxlen = max(maxlen,len(sequence[i]))

print(X)
print(y)
print(maxlen)

[[20, 21, 22, 23, 2, 3, 7, 2], [2, 4, 24, 25, 26, 7, 1, 27], [1, 3, 28, 13, 8, 29, 30, 31, 32, 33, 5], [1, 3, 13, 35, 1], [37, 14, 15, 38, 1, 4, 6, 39, 16, 7, 2], [1, 4, 40, 1], [17, 42, 43, 6, 2, 10, 5, 44, 16, 6, 45, 18, 2, 46, 5, 1, 10], [48, 14, 1, 3, 5, 1, 4, 49, 1], [17, 51, 52, 6, 53, 1], [18, 1, 10, 54, 1, 55, 1, 56, 57, 58], [1, 3, 11, 8], [61, 1, 4, 11, 8], [63, 2, 64, 65, 1, 3, 66, 6, 19, 5, 67, 68, 19, 15, 69], [1, 4, 11, 71, 5, 72, 1, 3, 7, 1]]
[[20, 21, 22, 23, 2, 3, 7, 2, 12], [2, 4, 24, 25, 26, 7, 1, 27, 12], [1, 3, 28, 13, 8, 29, 30, 31, 32, 33, 5, 34], [1, 3, 13, 35, 1, 36], [37, 14, 15, 38, 1, 4, 6, 39, 16, 7, 2, 9], [1, 4, 40, 1, 41], [17, 42, 43, 6, 2, 10, 5, 44, 16, 6, 45, 18, 2, 46, 5, 1, 10, 47], [48, 14, 1, 3, 5, 1, 4, 49, 1, 50], [17, 51, 52, 6, 53, 1, 9], [18, 1, 10, 54, 1, 55, 1, 56, 57, 58, 59], [1, 3, 11, 8, 60], [61, 1, 4, 11, 8, 62], [63, 2, 64, 65, 1, 3, 66, 6, 19, 5, 67, 68, 19, 15, 69, 70], [1, 4, 11, 71, 5, 72, 1, 3, 7, 1, 9]]
18


In [ ]:
X = pad_sequences(X,maxlen = maxlen+1, padding = 'pre')
print(X)
y = pad_sequences(y, maxlen = maxlen+1, padding = 'pre')
print(y)

[[ 0  0  0  0  0  0  0  0  0  0  0 20 21 22 23  2  3  7  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  4 24 25 26  7  1 27]
 [ 0  0  0  0  0  0  0  0  1  3 28 13  8 29 30 31 32 33  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  3 13 35  1]
 [ 0  0  0  0  0  0  0  0 37 14 15 38  1  4  6 39 16  7  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  4 40  1]
 [ 0  0 17 42 43  6  2 10  5 44 16  6 45 18  2 46  5  1 10]
 [ 0  0  0  0  0  0  0  0  0  0 48 14  1  3  5  1  4 49  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 17 51 52  6 53  1]
 [ 0  0  0  0  0  0  0  0  0 18  1 10 54  1 55  1 56 57 58]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  3 11  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 61  1  4 11  8]
 [ 0  0  0  0 63  2 64 65  1  3 66  6 19  5 67 68 19 15 69]
 [ 0  0  0  0  0  0  0  0  0  1  4 11 71  5 72  1  3  7  1]]
[[ 0  0  0  0  0  0  0  0  0  0 20 21 22 23  2  3  7  2 12]
 [ 0  0  0  0  0  0  0  0  0  0  2  4 24 25 26  7  1 27 12]
 [ 0  0  0  0  0  0  0  1  3 28 13  8 2

In [ ]:
y = to_categorical(y,vocab_size)
y

array([[[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
model = Sequential()
model.add(Embedding(input_dim = vocab_size,output_dim=50))
model.add(SimpleRNN(units=70,return_sequences = True))
model.add(Dense(units=vocab_size,activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 50)          3650      
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, None, 70)          8470      
_________________________________________________________________
dense_1 (Dense)              (None, None, 73)          5183      
Total params: 17,303
Trainable params: 17,303
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print("input shape of all layers:",model.layers[0].input_shape,model.layers[1].input_shape,model.layers[2].input_shape)

input shape of all layers: (None, None) (None, None, 50) (None, None, 70)


In [ ]:
model.compile(optimizer='rmsprop',loss = 'categorical_crossentropy',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=1)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 4.2977 - accuracy: 0.0038
Epoch 2/200
1/1 [==============================] - 0s 15ms/step - loss: 4.1306 - accuracy: 0.4398
Epoch 3/200
1/1 [==============================] - 0s 12ms/step - loss: 3.9400 - accuracy: 0.4323
Epoch 4/200
1/1 [==============================] - 0s 13ms/step - loss: 3.7283 - accuracy: 0.4850
Epoch 5/200
1/1 [==============================] - 0s 12ms/step - loss: 3.5308 - accuracy: 0.4850
Epoch 6/200
1/1 [==============================] - 0s 11ms/step - loss: 3.3651 - accuracy: 0.4850
Epoch 7/200
1/1 [==============================] - 0s 14ms/step - loss: 3.2266 - accuracy: 0.4850
Epoch 8/200
1/1 [==============================] - 0s 12ms/step - loss: 3.1091 - accuracy: 0.4850
Epoch 9/200
1/1 [==============================] - 0s 15ms/step - loss: 3.0422 - accuracy: 0.5113
Epoch 10/200
1/1 [==============================] - 0s 8ms/step - loss: 3.0999 - accuracy: 0.4850
Epoch 11/200
1/1 [====

# Sampling sentences

In [ ]:
def sample_sentences(model, tokenizer, num_words,vocab_size):
  encoded = []
  text = ''
  for i in range(num_words):
    encoded = tokenizer.texts_to_sequences([text])[0]
    encoded.insert(0,0)
    encoded = array(encoded)
    encoded = numpy.reshape(encoded,newshape=(1,-1))

    print("\nFor:",i,"Encoded:",encoded,encoded.shape)
    if i == 0:
      probability = model.predict_proba(encoded, verbose = 1)
      print("\nFor:",i,"Probability:",probability,type(probability),probability.shape)
      yhat = 0
      while(yhat == 0):
        yhat = numpy.random.choice(range(vocab_size),p=probability.ravel())
      yhat = [yhat]
      yhat = array(yhat)
      yhat = numpy.reshape(yhat,newshape = (1,-1))
    else:
      probability = model.predict_proba(encoded,verbose=1)
      print("\nFor:",i,"Probability:",probability,type(probability),probability.shape)
      yhat = numpy.append(yhat,0)
      yhat = numpy.reshape(yhat,newshape=(1,-1))
      while yhat[0,i] == 0:
        yhat[0,i] = numpy.random.choice(range(vocab_size),p=probability[0,i].ravel())
    print("\nFor:",i,"Else yhat:",yhat,yhat.shape)

    out_word = ''
    for word,index in tokenizer.word_index.items():
      if index == yhat[0,i]:
        out_word = word
        break

    text = text + out_word + ' '
  return text


In [ ]:
print("\n",sample_sentences(model,tokenizer,10,vocab_size))


For: 0 Encoded: [[0]] (1, 1)
1/1 [==============================] - 0s 153ms/step

For: 0 Probability: [[[9.1556132e-01 9.3264105e-03 7.6861307e-03 6.1861915e-04 1.6169349e-04
   1.0149505e-04 1.5636340e-04 2.8693880e-04 1.3028407e-04 3.9945988e-04
   1.2508224e-04 9.1921298e-05 8.7516109e-04 4.8540762e-05 1.7992168e-04
   6.4224980e-05 9.9147088e-04 1.8503729e-02 5.8056726e-03 7.6569675e-05
   3.4095175e-03 6.0114678e-04 2.5657599e-04 8.3499216e-04 1.8208560e-04
   2.0420003e-04 6.2724706e-05 8.1387130e-05 1.3769536e-04 3.5878726e-05
   4.4252836e-05 1.4058976e-04 3.6217866e-04 7.8434945e-04 1.2331272e-03
   2.1152517e-04 4.8340964e-05 4.1303863e-03 9.3135046e-04 4.6385641e-04
   1.1446382e-04 6.8444177e-05 1.3534480e-03 2.7493032e-04 6.5083569e-04
   8.3333667e-04 3.6792652e-04 1.6109599e-04 3.5500417e-03 3.8365633e-05
   4.8900434e-05 7.3420008e-05 4.5301873e-05 8.9369576e-05 2.1082151e-04
   2.9463539e-05 4.6771343e-05 1.5603857e-05 3.1587766e-05 3.3960321e-05
   7.3749208e-05 5.2

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


1/1 [==============================] - 0s 150ms/step

For: 1 Probability: [[[9.15561318e-01 9.32640210e-03 7.68612279e-03 6.18618564e-04
   1.61693490e-04 1.01495047e-04 1.56363254e-04 2.86938506e-04
   1.30283937e-04 3.99459503e-04 1.25082122e-04 9.19211234e-05
   8.75160214e-04 4.85406745e-05 1.79921510e-04 6.42249142e-05
   9.91469948e-04 1.85037106e-02 5.80566749e-03 7.65696750e-05
   3.40951257e-03 6.01145905e-04 2.56575760e-04 8.34991341e-04
   1.82085423e-04 2.04199823e-04 6.27246482e-05 8.13870574e-05
   1.37695228e-04 3.58786929e-05 4.42527926e-05 1.40589633e-04
   3.62178485e-04 7.84348696e-04 1.23312604e-03 2.11524966e-04
   4.83409203e-05 4.13038395e-03 9.31349641e-04 4.63855773e-04
   1.14463714e-04 6.84441111e-05 1.35344674e-03 2.74930324e-04
   6.50835049e-04 8.33335856e-04 3.67926172e-04 1.61095842e-04
   3.55003821e-03 3.83655570e-05 4.89003942e-05 7.34199421e-05
   4.53018292e-05 8.93694887e-05 2.10821308e-04 2.94635392e-05
   4.67712998e-05 1.56038568e-05 3.15877041e

# Generating sentences

In [ ]:
def generate_sentences(model, tokenizer, num_words,vocab_size):
  encoded = []
  text = ''
  for i in range(num_words):
    encoded = tokenizer.texts_to_sequences([text])[0]
    encoded.insert(0,0)
    encoded = array(encoded)
    encoded = numpy.reshape(encoded,newshape=(1,-1))

    print("For:",i,"Encoded:",encoded,encoded.shape)
    if i == 0:
      probability = model.predict_proba(encoded, verbose = 0)
      print("\nFor:",i,"Probability:",probability,type(probability),probability.shape)
      yhat = 0
      while(yhat == 0):
        yhat = numpy.random.choice(range(vocab_size),p=probability.ravel())
      yhat = [yhat]
      yhat = array(yhat)
      yhat = numpy.reshape(yhat,newshape = (1,-1))
    else:
      probability = model.predict_proba(encoded,verbose=0)
      print("\nFor:",i,"Probability:",probability,type(probability),probability.shape)
      yhat = numpy.append(yhat,0)
      yhat = numpy.reshape(yhat,newshape=(1,-1))
      yhat[0, i] = np.argmax(probability[0, i].ravel()[1:], axis=0)
      print("\nFor:",i,"Else yhat:",yhat,yhat.shape)

    out_word = ''
    for word,index in tokenizer.word_index.items():
      if index == yhat[0,i]:
        out_word = word
        break

    text = text + out_word + ' '
  return text


In [ ]:
print("\n",generate_sentences(model,tokenizer,8,vocab_size))

For: 0 Encoded: [[0]] (1, 1)

For: 0 Probability: [[[9.1556132e-01 9.3264105e-03 7.6861307e-03 6.1861915e-04 1.6169349e-04
   1.0149505e-04 1.5636340e-04 2.8693880e-04 1.3028407e-04 3.9945988e-04
   1.2508224e-04 9.1921298e-05 8.7516109e-04 4.8540762e-05 1.7992168e-04
   6.4224980e-05 9.9147088e-04 1.8503729e-02 5.8056726e-03 7.6569675e-05
   3.4095175e-03 6.0114678e-04 2.5657599e-04 8.3499216e-04 1.8208560e-04
   2.0420003e-04 6.2724706e-05 8.1387130e-05 1.3769536e-04 3.5878726e-05
   4.4252836e-05 1.4058976e-04 3.6217866e-04 7.8434945e-04 1.2331272e-03
   2.1152517e-04 4.8340964e-05 4.1303863e-03 9.3135046e-04 4.6385641e-04
   1.1446382e-04 6.8444177e-05 1.3534480e-03 2.7493032e-04 6.5083569e-04
   8.3333667e-04 3.6792652e-04 1.6109599e-04 3.5500417e-03 3.8365633e-05
   4.8900434e-05 7.3420008e-05 4.5301873e-05 8.9369576e-05 2.1082151e-04
   2.9463539e-05 4.6771343e-05 1.5603857e-05 3.1587766e-05 3.3960321e-05
   7.3749208e-05 5.2513322e-03 3.4057168e-05 8.2750358e-03 3.5510998e-04
 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '



For: 4 Probability: [[[9.15561318e-01 9.32641048e-03 7.68613070e-03 6.18619146e-04
   1.61693490e-04 1.01495047e-04 1.56363400e-04 2.86938797e-04
   1.30284068e-04 3.99459881e-04 1.25082239e-04 9.19212980e-05
   8.75161088e-04 4.85407618e-05 1.79921684e-04 6.42249797e-05
   9.91470879e-04 1.85037293e-02 5.80567261e-03 7.65696750e-05
   3.40951746e-03 6.01146778e-04 2.56575993e-04 8.34992155e-04
   1.82085598e-04 2.04200027e-04 6.27247064e-05 8.13871302e-05
   1.37695359e-04 3.58787256e-05 4.42528362e-05 1.40589764e-04
   3.62178660e-04 7.84349453e-04 1.23312720e-03 2.11525170e-04
   4.83409640e-05 4.13038628e-03 9.31350456e-04 4.63856413e-04
   1.14463823e-04 6.84441766e-05 1.35344802e-03 2.74930324e-04
   6.50835689e-04 8.33336671e-04 3.67926521e-04 1.61095988e-04
   3.55004170e-03 3.83656334e-05 4.89004342e-05 7.34200075e-05
   4.53018729e-05 8.93695760e-05 2.10821512e-04 2.94635392e-05
   4.67713435e-05 1.56038568e-05 3.15877660e-05 3.39603212e-05
   7.37492082e-05 5.25133219e-03 3